export enum SandboxViolationCode {
  EMPTY_SQL = 'EMPTY_SQL',
  MULTI_STATEMENT = 'MULTI_STATEMENT',
  DISALLOWED_STATEMENT = 'DISALLOWED_STATEMENT',
  BLOCKED_PATTERN = 'BLOCKED_PATTERN',
  NON_PARAMETERIZED = 'NON_PARAMETERIZED',
  QUERY_TIMEOUT = 'QUERY_TIMEOUT',
  ROW_LIMIT_EXCEEDED = 'ROW_LIMIT_EXCEEDED',
  EXECUTION_FAILED = 'EXECUTION_FAILED',
}
