export enum JobFailureReason {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  SESSION_UNAVAILABLE = 'SESSION_UNAVAILABLE',
  TIMEOUT = 'TIMEOUT',
  EXECUTION_ERROR = 'EXECUTION_ERROR',
  STORAGE_ERROR = 'STORAGE_ERROR',
  QUEUE_UNAVAILABLE = 'QUEUE_UNAVAILABLE',
  RATE_LIMITED = 'RATE_LIMITED',
}

export const JOB_FAILURE_REASONS = Object.values(JobFailureReason);
